//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KavoshFrameWorkWebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Entities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KavoshFrameWorkWebApplication.Resources.Entities", typeof(Entities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی.
        /// </summary>
        public static string ApplicationRole {
            get {
                return ResourceManager.GetString("ApplicationRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string ApplicationUser {
            get {
                return ResourceManager.GetString("ApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرجع تصویب.
        /// </summary>
        public static string ApprovalRefrence {
            get {
                return ResourceManager.GetString("ApprovalRefrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بودجه.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه.
        /// </summary>
        public static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکای تجاری.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع شرکت.
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرارداد.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفت برنامه ای.
        /// </summary>
        public static string Develop {
            get {
                return ResourceManager.GetString("Develop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفت واقعی.
        /// </summary>
        public static string DevelopReal {
            get {
                return ResourceManager.GetString("DevelopReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دامین.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران دامین.
        /// </summary>
        public static string DomainUser {
            get {
                return ResourceManager.GetString("DomainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم ها.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف گروه بندی.
        /// </summary>
        public static string GroupProject {
            get {
                return ResourceManager.GetString("GroupProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاخص.
        /// </summary>
        public static string IndexData {
            get {
                return ResourceManager.GetString("IndexData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش بصورت لیست.
        /// </summary>
        public static string ListOnly {
            get {
                return ResourceManager.GetString("ListOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاهای سیستمی.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه منو.
        /// </summary>
        public static string ParentTitle {
            get {
                return ResourceManager.GetString("ParentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصول موضوعه.
        /// </summary>
        public static string Principle {
            get {
                return ResourceManager.GetString("Principle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الویت.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات اولیه.
        /// </summary>
        public static string ProjectBaseInfo {
            get {
                return ResourceManager.GetString("ProjectBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بودجه پروژه.
        /// </summary>
        public static string ProjectBudget {
            get {
                return ResourceManager.GetString("ProjectBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزء پروژه.
        /// </summary>
        public static string ProjectDetail {
            get {
                return ResourceManager.GetString("ProjectDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه.
        /// </summary>
        public static string ProjectId {
            get {
                return ResourceManager.GetString("ProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اهداف راهبردی.
        /// </summary>
        public static string ProjectTarget {
            get {
                return ResourceManager.GetString("ProjectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع پروژه.
        /// </summary>
        public static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیاست های مقاومتی.
        /// </summary>
        public static string ResistancePolicy {
            get {
                return ResourceManager.GetString("ResistancePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی.
        /// </summary>
        public static string RoleFormActionAssignment {
            get {
                return ResourceManager.GetString("RoleFormActionAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصیص عملیات.
        /// </summary>
        public static string RolesActionAssignment {
            get {
                return ResourceManager.GetString("RolesActionAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string RoleTypeId {
            get {
                return ResourceManager.GetString("RoleTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماژول.
        /// </summary>
        public static string SystemForm {
            get {
                return ResourceManager.GetString("SystemForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string SystemRoles {
            get {
                return ResourceManager.GetString("SystemRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل بودجه.
        /// </summary>
        public static string TotlaBudget {
            get {
                return ResourceManager.GetString("TotlaBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساختار درختی.
        /// </summary>
        public static string TreeCategory {
            get {
                return ResourceManager.GetString("TreeCategory", resourceCulture);
            }
        }
    }
}
