//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KavoshFrameWorkWebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KavoshFrameWorkWebApplication.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حق حضور کمیته حسابرسی(ریال).
        /// </summary>
        public static string AccountingRight {
            get {
                return ResourceManager.GetString("AccountingRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقدامات انجام شده توسط شرکت.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string AddedDate {
            get {
                return ResourceManager.GetString("AddedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماینده.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل اشتغال نماینده.
        /// </summary>
        public static string AgentCompanyTitle {
            get {
                return ResourceManager.GetString("AgentCompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن نماینده.
        /// </summary>
        public static string AgentPhone {
            get {
                return ResourceManager.GetString("AgentPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نماینده.
        /// </summary>
        public static string AgentsNumber {
            get {
                return ResourceManager.GetString("AgentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماینده.
        /// </summary>
        public static string AgentTitle {
            get {
                return ResourceManager.GetString("AgentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد تجمعی گروه.
        /// </summary>
        public static string AggregatePercentage {
            get {
                return ResourceManager.GetString("AggregatePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه محاسبه.
        /// </summary>
        public static string AggregatePercentageCalculationType {
            get {
                return ResourceManager.GetString("AggregatePercentageCalculationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string ApplicationUserId {
            get {
                return ResourceManager.GetString("ApplicationUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انتصاب.
        /// </summary>
        public static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تصویب.
        /// </summary>
        public static string ApprovalDate {
            get {
                return ResourceManager.GetString("ApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرجع تصویب.
        /// </summary>
        public static string ApprovalRefrenceId {
            get {
                return ResourceManager.GetString("ApprovalRefrenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تصویب.
        /// </summary>
        public static string AprovalDate {
            get {
                return ResourceManager.GetString("AprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرجع تصویب.
        /// </summary>
        public static string AprovalRefrence {
            get {
                return ResourceManager.GetString("AprovalRefrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مجمع.
        /// </summary>
        public static string AssemblyType {
            get {
                return ResourceManager.GetString("AssemblyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکالیف محوله مجمع در خصوص بندهای حسابرسی و بازرسی قانونی.
        /// </summary>
        public static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسهیلات ارزی بانکی.
        /// </summary>
        public static string BankFacilitiesCurrency {
            get {
                return ResourceManager.GetString("BankFacilitiesCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسهیلات بانکی میلیون ریال.
        /// </summary>
        public static string BankFacilitiesRial {
            get {
                return ResourceManager.GetString("BankFacilitiesRial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاداش هیات مدیره(میلیون ریال).
        /// </summary>
        public static string BoardBonus {
            get {
                return ResourceManager.GetString("BoardBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام عضو حقوقی هیات مدیره.
        /// </summary>
        public static string BoardofDirectorsLegalMemberTitle {
            get {
                return ResourceManager.GetString("BoardofDirectorsLegalMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حق حضور اعضای هیات مدیره(ریال).
        /// </summary>
        public static string BoardRight {
            get {
                return ResourceManager.GetString("BoardRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بودجه.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بودجه.
        /// </summary>
        public static string BudgetId {
            get {
                return ResourceManager.GetString("BudgetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد بورس.
        /// </summary>
        public static string BurseCode {
            get {
                return ResourceManager.GetString("BurseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از مبلغ (ریال).
        /// </summary>
        public static string CapitalChangeFrom {
            get {
                return ResourceManager.GetString("CapitalChangeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد تغییرات سرمایه.
        /// </summary>
        public static string CapitalChangePercentage {
            get {
                return ResourceManager.GetString("CapitalChangePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا مبلغ (ریال).
        /// </summary>
        public static string CapitalChangeTo {
            get {
                return ResourceManager.GetString("CapitalChangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد افزایش سرمایه از محل سود انباشته.
        /// </summary>
        public static string CapitalIncreaseFromAccumulatedProfits {
            get {
                return ResourceManager.GetString("CapitalIncreaseFromAccumulatedProfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد افزایش سرمایه از تجدید ارزیابی دارایی ها.
        /// </summary>
        public static string CapitalIncreaseFromAssetsRevaluation {
            get {
                return ResourceManager.GetString("CapitalIncreaseFromAssetsRevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد افزایش سرمایه آورده نقدی.
        /// </summary>
        public static string CapitalIncreaseFromCash {
            get {
                return ResourceManager.GetString("CapitalIncreaseFromCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد افزایش سرمایه مطالبات حاصل شده سهامداران.
        /// </summary>
        public static string CapitalIncreaseFromShareholderReceivables {
            get {
                return ResourceManager.GetString("CapitalIncreaseFromShareholderReceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیرعامل.
        /// </summary>
        public static string CEO {
            get {
                return ResourceManager.GetString("CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن مدیرعامل.
        /// </summary>
        public static string CEOPhone {
            get {
                return ResourceManager.GetString("CEOPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعضای گروه.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت همکار.
        /// </summary>
        public static string Colleague {
            get {
                return ResourceManager.GetString("Colleague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت بازرگانی.
        /// </summary>
        public static string CommercialCard {
            get {
                return ResourceManager.GetString("CommercialCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شرکت.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فعالیت شرکت.
        /// </summary>
        public static string CompanyActivityTypeTitle {
            get {
                return ResourceManager.GetString("CompanyActivityTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید شرکت.
        /// </summary>
        public static string CompanyConfirm {
            get {
                return ResourceManager.GetString("CompanyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت.
        /// </summary>
        public static string CompanyId {
            get {
                return ResourceManager.GetString("CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سهامی شرکت.
        /// </summary>
        public static string CompanyPartnershipTypeTitle {
            get {
                return ResourceManager.GetString("CompanyPartnershipTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت.
        /// </summary>
        public static string CompanyTitle {
            get {
                return ResourceManager.GetString("CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کمپانی.
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کمپانی.
        /// </summary>
        public static string CompanyTypeId {
            get {
                return ResourceManager.GetString("CompanyTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع شرکت.
        /// </summary>
        public static string CompanyTypeTitle {
            get {
                return ResourceManager.GetString("CompanyTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اتمام.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید رمز عبور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرارداد.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره قرارداد.
        /// </summary>
        public static string ContractNo {
            get {
                return ResourceManager.GetString("ContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت قرارداد.
        /// </summary>
        public static string ContractState {
            get {
                return ResourceManager.GetString("ContractState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع قرارداد.
        /// </summary>
        public static string ContractSubject {
            get {
                return ResourceManager.GetString("ContractSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع قرارداد.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرمایه فعلی (ریال).
        /// </summary>
        public static string CurrentCapital {
            get {
                return ResourceManager.GetString("CurrentCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد سهام جدید.
        /// </summary>
        public static string CurrentShares {
            get {
                return ResourceManager.GetString("CurrentShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصمیمات مجمع.
        /// </summary>
        public static string Decisions {
            get {
                return ResourceManager.GetString("Decisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد پیشرفت.
        /// </summary>
        public static string DevelopePercent {
            get {
                return ResourceManager.GetString("DevelopePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سود تقسیمی(ریال).
        /// </summary>
        public static string DividedProfit {
            get {
                return ResourceManager.GetString("DividedProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دامین.
        /// </summary>
        public static string DomainId {
            get {
                return ResourceManager.GetString("DomainId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دامین.
        /// </summary>
        public static string DomainIds {
            get {
                return ResourceManager.GetString("DomainIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اقتصادی.
        /// </summary>
        public static string EconomicCode {
            get {
                return ResourceManager.GetString("EconomicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدرک تحصیلی.
        /// </summary>
        public static string EducationDegreeTitle {
            get {
                return ResourceManager.GetString("EducationDegreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن مصوبه.
        /// </summary>
        public static string EnactmentDetails {
            get {
                return ResourceManager.GetString("EnactmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان مصوبه.
        /// </summary>
        public static string EnactmentTitle {
            get {
                return ResourceManager.GetString("EnactmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم ها.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تاسیس.
        /// </summary>
        public static string EstablishmentDate {
            get {
                return ResourceManager.GetString("EstablishmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فکس.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین برآورد دوره برگشت سرمایه.
        /// </summary>
        public static string FeedbackFound {
            get {
                return ResourceManager.GetString("FeedbackFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرخ بازده داخلی.
        /// </summary>
        public static string FeedbackRate {
            get {
                return ResourceManager.GetString("FeedbackRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته.
        /// </summary>
        public static string Filed {
            get {
                return ResourceManager.GetString("Filed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیر مالی.
        /// </summary>
        public static string FinancialManager {
            get {
                return ResourceManager.GetString("FinancialManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن مدیر مالی.
        /// </summary>
        public static string FinancialManagerPhone {
            get {
                return ResourceManager.GetString("FinancialManagerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتمام پروژه.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آورده ارزی سازمان.
        /// </summary>
        public static string FirmCurrency {
            get {
                return ResourceManager.GetString("FirmCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آورده سازمان میلیون ریال.
        /// </summary>
        public static string FirmRial {
            get {
                return ResourceManager.GetString("FirmRial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال مالی.
        /// </summary>
        public static string FiscalYearTitle {
            get {
                return ResourceManager.GetString("FiscalYearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت فرم.
        /// </summary>
        public static string FormStatus {
            get {
                return ResourceManager.GetString("FormStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string FormStatusComments {
            get {
                return ResourceManager.GetString("FormStatusComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره برگشت سرمایه.
        /// </summary>
        public static string FundReturn {
            get {
                return ResourceManager.GetString("FundReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمک های ارزی دولتی.
        /// </summary>
        public static string GovermentCurrency {
            get {
                return ResourceManager.GetString("GovermentCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمک های دولتی میلیون ریال.
        /// </summary>
        public static string GovermentRial {
            get {
                return ResourceManager.GetString("GovermentRial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هلدینگ.
        /// </summary>
        public static string Holding {
            get {
                return ResourceManager.GetString("Holding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید کمپانی.
        /// </summary>
        public static string HoldingConfirm {
            get {
                return ResourceManager.GetString("HoldingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آورده ارزی هلدینگ.
        /// </summary>
        public static string HoldingCurrency {
            get {
                return ResourceManager.GetString("HoldingCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آورده هلدینگ میلیون ریال.
        /// </summary>
        public static string HoldingRial {
            get {
                return ResourceManager.GetString("HoldingRial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد سهام هلدینگ در مجمع.
        /// </summary>
        public static string HoldingShares {
            get {
                return ResourceManager.GetString("HoldingShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین برآورد مدت اجرای طرح.
        /// </summary>
        public static string ImplemetationRate {
            get {
                return ResourceManager.GetString("ImplemetationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاسبه در فرمول.
        /// </summary>
        public static string IncludeInFormula {
            get {
                return ResourceManager.GetString("IncludeInFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاخص.
        /// </summary>
        public static string IndexData {
            get {
                return ResourceManager.GetString("IndexData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاخص.
        /// </summary>
        public static string IndexDataId {
            get {
                return ResourceManager.GetString("IndexDataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاخص ها.
        /// </summary>
        public static string IndexDatas {
            get {
                return ResourceManager.GetString("IndexDatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین برآورد نرخ بازدهی داخلی.
        /// </summary>
        public static string InnerFeedbackRate {
            get {
                return ResourceManager.GetString("InnerFeedbackRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منابع ارزی داخلی شرکت.
        /// </summary>
        public static string InnerSourceCurrency {
            get {
                return ResourceManager.GetString("InnerSourceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منابع داخلی شرکت میلیون ریال.
        /// </summary>
        public static string InnerSourceRial {
            get {
                return ResourceManager.GetString("InnerSourceRial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بیمه.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سهامدار اصلی.
        /// </summary>
        public static string IsMainShareholder {
            get {
                return ResourceManager.GetString("IsMainShareholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین مجمع انتخاب اعضای هیات مدیره.
        /// </summary>
        public static string LastElectionMeetingDate {
            get {
                return ResourceManager.GetString("LastElectionMeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع آخرین برآورد.
        /// </summary>
        public static string LastEstimate {
            get {
                return ResourceManager.GetString("LastEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع عضو حقیقی.
        /// </summary>
        public static string LegalMemberTypeTitle {
            get {
                return ResourceManager.GetString("LegalMemberTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پایه.
        /// </summary>
        public static string ListOnly {
            get {
                return ResourceManager.GetString("ListOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه اصلی.
        /// </summary>
        public static string MainGroupTitle {
            get {
                return ResourceManager.GetString("MainGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ جلسه.
        /// </summary>
        public static string MeetingDate {
            get {
                return ResourceManager.GetString("MeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع مجمع.
        /// </summary>
        public static string MeetingSubject {
            get {
                return ResourceManager.GetString("MeetingSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ملی.
        /// </summary>
        public static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت در روزنامه رسمی.
        /// </summary>
        public static string NewspaperEntryDate {
            get {
                return ResourceManager.GetString("NewspaperEntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روزنامه رسمی.
        /// </summary>
        public static string NewspaperTitle {
            get {
                return ResourceManager.GetString("NewspaperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اعضای هیات مدیره.
        /// </summary>
        public static string NumberOfCompanyBoardMembers {
            get {
                return ResourceManager.GetString("NumberOfCompanyBoardMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور قبلی.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پروانه بهره برداری.
        /// </summary>
        public static string OperationLicenseNumber {
            get {
                return ResourceManager.GetString("OperationLicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سفارش.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سِمت.
        /// </summary>
        public static string OrganizationalPositionTitle {
            get {
                return ResourceManager.GetString("OrganizationalPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید سازمان.
        /// </summary>
        public static string OrganizationConfirm {
            get {
                return ResourceManager.GetString("OrganizationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد مالکیت.
        /// </summary>
        public static string OwnershipPercentage {
            get {
                return ResourceManager.GetString("OwnershipPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر گروه.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه منو.
        /// </summary>
        public static string ParentTitle {
            get {
                return ResourceManager.GetString("ParentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشارکت ارزی.
        /// </summary>
        public static string ParticipationCurrency {
            get {
                return ResourceManager.GetString("ParticipationCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشارکت میلیون ریال.
        /// </summary>
        public static string ParticipationRial {
            get {
                return ResourceManager.GetString("ParticipationRial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش اسمی هر سهم (ریال).
        /// </summary>
        public static string ParValue {
            get {
                return ResourceManager.GetString("ParValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداختی پیمانکار.
        /// </summary>
        public static string PaymentColleague {
            get {
                return ResourceManager.GetString("PaymentColleague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورت وضعیت پرداخت نشده.
        /// </summary>
        public static string PaymentState {
            get {
                return ResourceManager.GetString("PaymentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت اجرای طرح-ماه.
        /// </summary>
        public static string PerformMonth {
            get {
                return ResourceManager.GetString("PerformMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدپستی.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرمایه قبلی (ریال).
        /// </summary>
        public static string PreviousCapital {
            get {
                return ResourceManager.GetString("PreviousCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد سهام قبلی.
        /// </summary>
        public static string PreviousShares {
            get {
                return ResourceManager.GetString("PreviousShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابرس اصلی.
        /// </summary>
        public static string PrimaryAuditorTitle {
            get {
                return ResourceManager.GetString("PrimaryAuditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصول موضوعه.
        /// </summary>
        public static string PrincipleId {
            get {
                return ResourceManager.GetString("PrincipleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصول موضوعه.
        /// </summary>
        public static string Principles {
            get {
                return ResourceManager.GetString("Principles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الویت.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string ProjectDate {
            get {
                return ResourceManager.GetString("ProjectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزء پروژه.
        /// </summary>
        public static string ProjectDetail {
            get {
                return ResourceManager.GetString("ProjectDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزء پروژه.
        /// </summary>
        public static string ProjectDetailId {
            get {
                return ResourceManager.GetString("ProjectDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه.
        /// </summary>
        public static string ProjectId {
            get {
                return ResourceManager.GetString("ProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اهداف راهبردی.
        /// </summary>
        public static string ProjectTargetId {
            get {
                return ResourceManager.GetString("ProjectTargetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اهداف راهبردی.
        /// </summary>
        public static string ProjectTargets {
            get {
                return ResourceManager.GetString("ProjectTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع طرح و پروژه.
        /// </summary>
        public static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع طرح و پروژه.
        /// </summary>
        public static string ProjectTypeId {
            get {
                return ResourceManager.GetString("ProjectTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رتبه.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت شده در اسناد مالی.
        /// </summary>
        public static string RegisterAmount {
            get {
                return ResourceManager.GetString("RegisterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل ثبت.
        /// </summary>
        public static string RegisterLocation {
            get {
                return ResourceManager.GetString("RegisterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ثبت.
        /// </summary>
        public static string RegisterNumber {
            get {
                return ResourceManager.GetString("RegisterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ثبت.
        /// </summary>
        public static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد ثبتی.
        /// </summary>
        public static string RegistrationUnit {
            get {
                return ResourceManager.GetString("RegistrationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مابقی مطالبات.
        /// </summary>
        public static string RemainDemands {
            get {
                return ResourceManager.GetString("RemainDemands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا به خاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بندگزارش حسابرس و بازرس قانونی.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ استعفا.
        /// </summary>
        public static string ResignationDate {
            get {
                return ResourceManager.GetString("ResignationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیاست های مقاومتی.
        /// </summary>
        public static string ResistancePolicies {
            get {
                return ResourceManager.GetString("ResistancePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیاست های مقاومتی.
        /// </summary>
        public static string ResistancePolicyId {
            get {
                return ResourceManager.GetString("ResistancePolicyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش ها.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string RoleType {
            get {
                return ResourceManager.GetString("RoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string RoleTypeId {
            get {
                return ResourceManager.GetString("RoleTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابرس علی البدل.
        /// </summary>
        public static string SecondaryAuditorTitle {
            get {
                return ResourceManager.GetString("SecondaryAuditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه خدمات.
        /// </summary>
        public static string ServiceCharge {
            get {
                return ResourceManager.GetString("ServiceCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا.
        /// </summary>
        public static string ShabaCode {
            get {
                return ResourceManager.GetString("ShabaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با هلدینگ توسط سهامدار.
        /// </summary>
        public static string ShareholderHoldingCommunication {
            get {
                return ResourceManager.GetString("ShareholderHoldingCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سهامدار.
        /// </summary>
        public static string ShareholderTitle {
            get {
                return ResourceManager.GetString("ShareholderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد سهم.
        /// </summary>
        public static string Shares {
            get {
                return ResourceManager.GetString("Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسئولیت های اجتماعی(میلیون ریال).
        /// </summary>
        public static string SocialResponsibility {
            get {
                return ResourceManager.GetString("SocialResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع برآورد اولیه.
        /// </summary>
        public static string StartEstimate {
            get {
                return ResourceManager.GetString("StartEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ بهره برداری برآورد اولیه.
        /// </summary>
        public static string StartEstimateUtilization {
            get {
                return ResourceManager.GetString("StartEstimateUtilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال شروع اجرا.
        /// </summary>
        public static string StartYear {
            get {
                return ResourceManager.GetString("StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ صورت وضعیت.
        /// </summary>
        public static string StatusStatmentDate {
            get {
                return ResourceManager.GetString("StatusStatmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه فرعی.
        /// </summary>
        public static string SubGroupTitle {
            get {
                return ResourceManager.GetString("SubGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سهامدار واسط.
        /// </summary>
        public static string SubShareholderTitle {
            get {
                return ResourceManager.GetString("SubShareholderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش ها.
        /// </summary>
        public static string SystemRoles {
            get {
                return ResourceManager.GetString("SystemRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش افزوده.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه کل.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سود کل(میلیون ریال).
        /// </summary>
        public static string TotalProfit {
            get {
                return ResourceManager.GetString("TotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل سهام.
        /// </summary>
        public static string TotalShares {
            get {
                return ResourceManager.GetString("TotalShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل بودجه.
        /// </summary>
        public static string TotlaBudget {
            get {
                return ResourceManager.GetString("TotlaBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه.
        /// </summary>
        public static string TreeViewData {
            get {
                return ResourceManager.GetString("TreeViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه.
        /// </summary>
        public static string TreeViewDataId {
            get {
                return ResourceManager.GetString("TreeViewDataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با هلدینگ تحت مدیریت.
        /// </summary>
        public static string UnderManagementHoldingCommunication {
            get {
                return ResourceManager.GetString("UnderManagementHoldingCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کننده.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ بهره برداری آخرین برآورد.
        /// </summary>
        public static string UtilizationDate {
            get {
                return ResourceManager.GetString("UtilizationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ حکم.
        /// </summary>
        public static string VerdictDate {
            get {
                return ResourceManager.GetString("VerdictDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
