//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KavoshFrameWorkWebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KavoshFrameWorkWebApplication.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی زمانی برای اعمال تغییرات به پایان رسیده است.
        /// </summary>
        public static string AccessDeadlineReached {
            get {
                return ResourceManager.GetString("AccessDeadlineReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درج آیتم برای آینده معتبر نمی باشد؛ لطفا تاریخ انتخاب شده را اصلاح نمایید.
        /// </summary>
        public static string CanNotAddItemOnFuture {
            get {
                return ResourceManager.GetString("CanNotAddItemOnFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییرات با موفقیت ذخیره شد..
        /// </summary>
        public static string ChangesSavedSuccessfully {
            get {
                return ResourceManager.GetString("ChangesSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل نباید از 512 کیلوبایت بیشتر باشد.
        /// </summary>
        public static string FileSizeExceeded {
            get {
                return ResourceManager.GetString("FileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شرکت شامل لوگو، مدیرعامل، تاریخ انتصاب، آدرس یا ... ناقص است. برای تایید فرم ابتدا پروفایل شرکت کامل شود.
        /// </summary>
        public static string IncompleteCompanyProfile {
            get {
                return ResourceManager.GetString("IncompleteCompanyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ وارد شده صحیح نمی باشد.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک فرمت مجاز تصویر شامل jpg,png یا gif انتخاب کنید.
        /// </summary>
        public static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا کلمه عبور اشتباه است.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دامین انتخاب شده اشتباه است..
        /// </summary>
        public static string InvaliDomainAttempt {
            get {
                return ResourceManager.GetString("InvaliDomainAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات غیر مجاز!.
        /// </summary>
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اعضای هیات مدیره شرکت باید حداکثر {0} نفر باشد.
        /// </summary>
        public static string MaxNumberOfBoardMembersReached {
            get {
                return ResourceManager.GetString("MaxNumberOfBoardMembersReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم مورد نظر حذف نشد؛ این ممکن است به دلیل وابستگی آیتم های دیگر به آن باشد. ابتدا وابستگی ها را حذف و سپس اقدام به حذف آیتم مورد نظر کنید.
        /// </summary>
        public static string ProblemDeletingItem {
            get {
                return ResourceManager.GetString("ProblemDeletingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف وارد شده تکراری است.
        /// </summary>
        public static string RedundantRowAdded {
            get {
                return ResourceManager.GetString("RedundantRowAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد الزامی می باشد.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
    }
}
